<?php

function ajax_actions_forms_ajax_actions_commands(&$action, &$options) {
  if ($action['op'] == 'process_form') {
    $form = ajax_actions_form_process($action, $options);
  }
  
  if ($action['op'] == 'node_add_form') {
    $form = ajax_actions_node_form_build($action, $options);
  }
  
  if ($action['op'] == 'node_edit_form') {
    $form = ajax_actions_node_form_build($action, $options);
  }
  
  if ($form) {
    if ($action['callback']) {
      $action['callback']($form, $action, $options);
    }
    else {
      $action['commands'][] = ajax_command_append($action['container'], render($form));
    }
    $action['break'] = TRUE;
  }
}

function ajax_actions_forms_form_alter(&$form, &$form_state, $form_id) {
  if ($form['actions'] && $form_state['build_info']['ajax']) {
    $ajax = $form_state['build_info']['ajax'];
    
    // Give ourselves a class to work with in case we need to replace this
    // markup at some point, for example if there is an error when submitting
    // the form.
    $class = 'ajax-actions-form-' . $ajax['ajax_actions']['settings']['dom_id'];
    $form['#attributes']['class'][] = $class;
    
    // Attach our js.
    $form['#attached']['js'][] = drupal_get_path('module', 'ajax_actions_forms') . '/scripts/ajax_actions_forms.js';
    
    // Add the #ajax array to the submit handlers.
    foreach (element_children($form['actions']) as $key) {
      $form['actions'][$key]['#ajax'] = $ajax;
    }
  }
}

function ajax_actions_form_process(&$action, &$options) {
  list($form, $form_state, $form_id, $form_build_id) = ajax_get_form();
  drupal_process_form($form['#form_id'], $form, $form_state);
  
  if (!$form_state['executed']) {
    if ($action['callback']) {
      return $form;
    }
    else {
      $selector = '.ajax-actions-form-' . $options['settings']['dom_id'];
      $action['commands'][] = ajax_command_replace($selector, render($form));
      $action['break'] = TRUE;
      return FALSE;
    }
  }
}

function ajax_actions_node_add($type, $settings = array()) {
  $defaults = array(
    'op' => 'node_add_form',
    'type' => $type,
    'container' => 'body',
  );
  
  $action = array_merge($defaults, $settings);
  
  return $action;
}

function ajax_actions_node_edit($nid, $settings = array()) {
  $defaults = array(
    'op' => 'node_edit_form',
    'nid' => $nid,
    'container' => 'body',
  );
  
  $action = array_merge($defaults, $settings);
  
  return $action;
}

function ajax_actions_node_add_form($type, $actions = array(), $settings = array(), $action = array()) {
  $defaults = array('type' => $type);
  
  $action = array_merge($action, $defaults);
  
  array_unshift($actions, $action);
  
  $options['actions'] = $actions;
  $options['settings'] = $settings;
  
  ajax_actions_defaults($options);
  
  $action = current($options['actions']);
  
  return ajax_actions_node_form_build($action, $options);
}

function ajax_actions_node_edit_form($nid, $actions = array(), $settings = array(), $action = array()) {
  $defaults = array('nid' => $nid);
  
  $action = array_merge($action, $defaults);
  
  array_unshift($actions, $action);
  
  $options['actions'] = $actions;
  $options['settings'] = $settings;
  
  ajax_actions_defaults($options);
  
  $action = current($options['actions']);
  
  return ajax_actions_node_form_build($action, $options);
}

function ajax_actions_node_form_build($action, $options) {
  global $user;
  
  if ($action['nid']) {
    $node = node_load($action['nid']);
  }
  else {
    $node = (object) array(
      'uid' => $user->uid,
      'name' => (isset($user->name) ? $user->name : ''),
      'type' => $action['type'],
      'language' => LANGUAGE_NONE,
    );
  }
  
  $type = $node->type;
  $form_id = $type . '_node_form';
  
  $ajax['settings'] = array();
  $ajax['actions'] = array_slice($options['actions'], array_search($action['delta'], array_keys($options['actions'])) + 1);
  
  $process = array('op' => 'process_form');
  $process['callback'] = $action['callback'] ? $action['callback'] : NULL;
  
  array_unshift($ajax['actions'], $process);
  
  ajax_actions_defaults($ajax);
  
  $form_state['build_info']['args']['node'] = $node;
  $form_state['build_info']['ajax'] = ajax_actions_build_ajax($ajax);
  
  if ($action['build_info']) {
    $form_state['build_info'] = array_merge($form_state['build_info'], $action['build_info']);
  }
  
  $form_state['cache'] = true;
  $form_state['build_info']['files'][] = array('type' => 'inc', 'module' => 'node', 'name' => 'node.pages');
  
  module_load_include('inc', 'node', 'node.pages');
  
  return drupal_build_form($form_id, $form_state);
}
