<?php

function ajax_actions_edit_field($field, $ids, $value = NULL, $settings = array()) {
  $defaults = array(
    'op' => 'edit_field',
    'field' => $field,
    'ids' => is_array($ids) ? $ids : array($ids),
    'value' => $value,
    'type' => 'node',
  );
  
  $action = array_merge($defaults, $settings);
  
  return $action;
}

function ajax_actions_edit_field_ajax_actions_commands($action) {
  if ($action['op'] == 'edit_field') {
    if ($action['ids']) {
      $field_info = field_info_field($action['field']);
      
      if ($field_info['cardinality'] == 1) {
        $entities = entity_load($action['type'], $action['ids']);
        
        foreach ($action['ids'] as $id) {
          $entity = entity_metadata_wrapper($action['type'], $entities[$id]);
          
          $entity->{$action['field']}->set($action['value']);
          $entity->save();
          drupal_set_message($entity->title->value() . ' has been updated.', 'status');
        }
      }
      else {
        drupal_set_message('You cannot set a multi value field\'s values using ajax actions edit field.', 'error');
      }
    }
  }
}